export {
  debounce,
  throttle,
  memoize,
} from './performance';

export {
  AppError,
  ValidationError,
  AuthenticationError,
  AuthorizationError,
  NotFoundError,
  NetworkError,
  TimeoutError,
  ServerError,
  RateLimitError,
  StreamError,
  ConfigurationError,
  isAppError,
  getErrorMessage,
  getErrorCode,
  formatErrorForUser,
  withErrorHandling,
  asyncWithErrorHandling,
  ErrorTracker,
} from './errors';

export {
  safeStorage,
  appStorage,
  LocalCache,
  Validator,
  validators,
  createValidator,
  validateField,
} from './storage';

export {
  useDebounce,
  useDebouncedCallback,
  useThrottle,
  useThrottledCallback,
  useLocalStorage,
  usePrevious,
  useWindowSize,
  useMediaQuery,
  useToggle,
  useArray,
  useInterval,
  useTimeout,
  useAsync,
  useHover,
  useClickOutside,
  useEventListener,
  useIsomorphicLayoutEffect,
  useCancellable,
} from './hooks';

export {
  formatBytes,
  formatDuration,
  formatTimestamp,
  truncate,
  capitalize,
  camelCase,
  snakeCase,
  kebabCase,
  pascalCase,
  slugify,
  uniq,
  uniqBy,
  groupBy,
  chunk,
  shuffle,
  sortBy,
  pick,
  omit,
  deepClone,
  deepEqual,
  isEmpty,
  isNil,
  clamp,
  lerp,
  randomInt,
  randomChoice,
  range,
  createQueue,
  parseJSON,
  stringifyJSON,
  getNestedValue,
  setNestedValue,
} from './helpers';

export {
  minimizeWindow,
  maximizeWindow,
  closeWindow,
  saveConfig,
  getAgentMode,
  setAgentMode,
  showOpenDialog,
  showSaveDialog,
  readFile,
  writeFile,
  deleteFile,
  listDirectory,
  startServer,
  stopServer,
  checkServerHealth,
  getServerStatus,
  startLlamaChat,
  startLlamaStream,
  checkLlamaHealth,
  stopLlama,
  listModels,
  downloadModel,
  deleteModel,
  switchModel,
  onServerMessage,
  onModelDownloadProgress,
  onModelLoaded,
  onModelError,
  isElectron,
  isDev,
  isProd,
  getPlatform,
} from './electron';

export {
  configureSecurity,
  getSecurityConfig,
  sanitizeHTML,
  escapeRegExp,
  escapeShell,
  validatePath,
  validateURL,
  validateEmail,
  maskSensitiveData,
  generateToken,
  hashString,
  timingSafeEqual,
  encodeBase64,
  decodeBase64,
  encodeBase64URL,
  decodeBase64URL,
  encryptData,
  decryptData,
  deriveKey,
  generateSalt,
  RateLimiter,
  rateLimiter,
  buildCSP,
  applySecurityHeaders,
} from './security';

export {
  Logger,
  LogLevel,
  LogEntry,
  LoggerConfig,
  ConsoleTransport,
  BufferTransport,
  RemoteTransport,
  FileTransport,
  logger,
  createLogger,
  withLogger,
  logAsync,
} from './logger';

export type {
  IpcClient,
  IpcError,
  IpcTimeoutError,
  IpcChannelError,
  IpcMain,
} from './ipc';

export {
  ipcClient,
  ipcMain,
  createIpcClient,
  createIpcMain,
  exposeApi,
  getExposedApi,
  createApiProxy,
  IpcChannels,
} from './ipc';

export {
  KeyboardShortcutRegistry,
  globalShortcutRegistry,
  useKeyboardShortcuts,
  useShortcutManager,
  formatShortcut,
  COMMON_SHORTCUTS,
} from './keyboard';

export type { KeyboardShortcut } from './keyboard';

export {
  string,
  number,
  boolean,
  array,
  object,
  required,
  optional,
  min,
  max,
  minLength,
  maxLength,
  pattern,
  enumType,
  custom,
  defaultValue,
  email,
  url,
  uuid,
  ip,
  appConfigSchema,
} from './validation';

export {
  MetricsCollector,
  PerformanceMonitor,
  metricsCollector,
  errorTracker,
  performanceMonitor,
  reportWebVitals,
  measureCLS,
  measureLCP,
  measureFID,
  measureTTFB,
  PerformanceMetric,
  MemoryMetric,
  NetworkMetric,
  CustomEvent,
} from './metrics';

export type {
  DeepPartial,
  DeepRequired,
  DeepReadonly,
  DeepNonNullable,
  PickRequired,
  PartialBy,
  Exactly,
  StringKeyOf,
  FunctionType,
  AsyncFunction,
  ConstructorType,
  Promisable,
  Awaited,
  Merge,
  Override,
  Diff,
  Intersection,
  Union,
  Nullable,
  OptionalNullable,
  EmptyObject,
  UnknownObject,
  AnyFunction,
  NoArgsFn,
  ValueOf,
  EntryOf,
  Keys,
  Values,
  MaybeArray,
  Flatten,
  DeepFlatten,
  IsAny,
  IsNever,
  IsUnknown,
  IsEqual,
  Writable,
  WritableDeep,
  Frozen,
  FrozenDeep,
  PropType,
  Paths,
  Leaves,
  TypeGuard,
  Schema,
} from '../types/extensions';

export {
  stringSchema,
  numberSchema,
  booleanSchema,
  objectSchema,
  arraySchema,
  unionSchema,
  optionalSchema,
  nullableSchema,
} from '../types/extensions';
